### ISSUE TITLE
remove name selection from landing page

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-frontend#103]
as a rates rebate applicant i don't want anyone to know who owns the property because it could expose my sensitive details

**Comment by leedowsett** [comment]
Is that really why we don't want to show that? It's public information.

**Comment by Br3nda** [comment]
Initial testingyshows it feels creepy. We also aren't handling the situation where the ratepayer has been marked private (there are some in this situation)

**Comment by Br3nda** [comment]
Fixed
