### ISSUE TITLE
Generate dates for the current year

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/pancake-frontend#149]
Front-end OpenFisca post

**Comment by MattiSG** [comment]
For example: the property name for the income should be `[ new Date().getFullYear() ]`, not `2018`. That will allow the software to update on its own over time, making use of the most recent definitions in OpenFisca without needing to update the frontend.

The year should be the current year, according to https://github.com/ServiceInnovationLab/openfisca-aotearoa/blob/feature/rates_rebate/openfisca_aotearoa/variables/ratesrebates.py#L62-L63

**Comment by Br3nda** [comment]
replaces #108
