### ISSUE TITLE
Add privacy statement

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-frontend#160]
Use Priv-o-matic to create statement and add to front end https://www.privacy.org.nz/further-resources/privacy-statement-generator/

**Comment by ssibbehh** [comment]
Privacy statement reviewed and approved by law. 


Privacy Statement:
We collect personal information from you, including information about your:
●      name;
●      contact information (including address, email address and phone number);
●      Income, including your partner’s;
●      number of dependants.
We collect your personal information in order to:
●      process your rates rebate application so that any rebate entitlement granted can be applied to your rates account or provide you with a refund, and it is not used for any other purposes than processing or granting a rates rebate.
Besides our staff, we share this information with:
●      the council that your property is governed by, in order to process your rates rebate application and if granted, apply a rebate to your account or provide you with a refund.
 
The council and the Department of Internal Affairs (DIA) are the recipients of this information.  DIA is the agency collecting this information as it is responsible for rates rebate administration.  DIA’s address is 45 Pipitea Street, PO Box 805, Wellington 6140.
 
Collection of this information is authorised by or under law by the Rates Rebate Act 1973 and the Contract and Commercial Law Act 2017. Providing some of this information is optional. If you choose not to enter information required on the form, we'll be unable to process your application and grant a rebate.
 
We keep your information for 7 years at which point we securely destroy it by securely erasing all digital forms and securely destroying all physical information.
 
You have the right to ask for a copy of any personal information we hold about you or your partner, and to ask for it to be corrected if you think it is wrong. If you’d like to ask for a copy of your information, or to have it corrected, please contact us at support@ratesrebates.govt.nz.

**Comment by dlouise64** [comment]
will place link in footer, which opens a modal
