### ISSUE TITLE
BUG: Breaking when pressing A multiple times on calculator

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-frontend#179]
![screen shot 2018-05-14 at 12 51 40 pm](https://user-images.githubusercontent.com/36939214/39973590-b44c93b4-5775-11e8-8d3d-f880ca0d67ea.png)
![screen shot 2018-05-14 at 12 49 44 pm](https://user-images.githubusercontent.com/36939214/39973591-b48af80c-5775-11e8-8c5f-c621fa09a62d.png)
![screen shot 2018-05-14 at 12 49 27 pm](https://user-images.githubusercontent.com/36939214/39973592-b4b58932-5775-11e8-8ff0-ebb378a5fa6d.png)

I got this from clicking into the address finder box, then pressing ```cmd a``` and ```control a``` repeatedly

**Comment by Br3nda** [comment]
what does cmd-a and control-a mean on your OS and browser? Is it "select all" ?

**Comment by Br3nda** [comment]
Fixed
