### ISSUE TITLE
Dependants is open text (remove arrows)

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-frontend#183]
![screen shot 2018-05-14 at 2 41 20 pm](https://user-images.githubusercontent.com/36939214/39975827-fa7f4106-5784-11e8-848d-da15ac4e2533.png)
![screen shot 2018-05-14 at 2 42 16 pm](https://user-images.githubusercontent.com/36939214/39975849-0737fbb8-5785-11e8-9302-d7594b2a6c30.png)

Needs to be radio button and drop down to ask number

**Comment by Br3nda** [comment]
bug still present. Will leave for tomorrow

**Comment by dlouise64** [comment]
closes ##234
