### ISSUE TITLE
Nice Income widget is lost in master 

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-frontend#185]
Now shows this older version:

![screen shot 2018-05-14 at 2 45 57 pm](https://user-images.githubusercontent.com/36939214/39975980-949bcafc-5785-11e8-86d6-905d0daf8a40.png)

@dlouise64  are you still working on this one in another branch before PR?

**Comment by Br3nda** [comment]
it's back.
