### ISSUE TITLE
Autofill changing address

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-frontend#196]
![screen shot 2018-05-15 at 10 35 38 am](https://user-images.githubusercontent.com/36939214/40026968-ce0eb83e-582b-11e8-8509-3409404c940f.png)

I pressed autofill and it changed the address. Need to prevent this from Autofilling ?

**Comment by ssibbehh** [comment]
This is Safari

**Comment by Br3nda** [comment]
fixed by making it not editable
