### ISSUE TITLE
Mobile responsiveness needs more padding

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-frontend#197]
![img_2966](https://user-images.githubusercontent.com/36939214/40031015-bf4a58b0-5841-11e8-9bfa-116fa11fddf3.PNG)
![img_2969](https://user-images.githubusercontent.com/36939214/40031017-bf74b236-5841-11e8-91cd-46b9efac3e63.PNG)
![img_2967](https://user-images.githubusercontent.com/36939214/40031018-bf9f3470-5841-11e8-8d52-3337eeb821fb.PNG)
![img_2968](https://user-images.githubusercontent.com/36939214/40031019-bfcbda98-5841-11e8-82cc-00a7ac84362f.PNG)

Tested on  iPhone SE (5s size) in safari

**Comment by Br3nda** [comment]
I added padding when i added the placeholder text. We'll need to use the same class when we take the placeholder off again.
