### ISSUE TITLE
Ready to sign page

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/pancake-frontend#22]
As an applicant, I receive a token (e.g. ABC) and take this with me to the city council office, so the CC staff can use token to look up the data I've entered and present it ready to be signed.

This story is only the code generation. The rest of the functionality is in later stories.

Acceptance criteria
- [ ] User enters application data using pancake web
- [ ] Token is displayed to the user
- [ ] User's data can be retrieved using this token

**Comment by ssibbehh** [comment]
[ ] Create UI/UX for this

**Comment by dlouise64** [comment]
Token is no longer displayed to the user. It is still being generated on the backend and should be used in url to access sign page:

eg. http*/#/XXXX-XXXX-XXX
