### ISSUE TITLE
Add rebate amount to signature form

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-frontend#223]

**Comment by ssibbehh** [comment]
Pull in rebate amount from back end, so it's not calling OpenFisca

**Comment by ssibbehh** [comment]
Brenda working on this Friday Morning

**Comment by Br3nda** [comment]
Server needs to calculate the rebate (it can ask open fisca)
It can't trust the value a browser submits.

So, i'll make a story to run the calculation on the servers too.
