### ISSUE TITLE
If you select partner and both on superannuation, then realise you need to remove your partner and so you deselect partner the total income remains at the higher income amount.

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-frontend#240]

**Comment by Br3nda** [comment]
Can give me the steps?
I've done this:

1) say yes i have a partner
2) give both super (they get 17458.48 ea)
3) said no to partner

the applicant then has $23058.36

What number are you getting? and what did you expect it to get instead?

**Comment by dlouise64** [comment]
@ssibbehh @Br3nda can I close this one?
