### ISSUE TITLE
Change timestamp from UTC to NZST

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-frontend#253]

**Comment by ssibbehh** [comment]
<img width="685" alt="time 01" src="https://user-images.githubusercontent.com/36939214/40291458-413aa678-5d19-11e8-82c1-660f9949a0a8.PNG">

This appears to be the only place displayed here

**Comment by Br3nda** [comment]
Fixed it up on the signature display too.
