### ISSUE TITLE
Priority -Add radio buttons under NZ Superannuation if they have a partner/joint homeowner

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-frontend#257]

**Comment by ssibbehh** [comment]
<img width="323" alt="superincome" src="https://user-images.githubusercontent.com/36939214/40291810-63ded990-5d1b-11e8-9c13-4a5d8f691010.PNG">

Like this but also with options for with partner

**Comment by ssibbehh** [comment]
Just realised that the schedule I have written that the spreadsheet doesn't include a couple of super income types!

**Comment by ssibbehh** [comment]
Married, civil union, or de facto couple, with non-qualified spouse included (each): $17281.68 
Married, civil union, or de facto couple, both qualify (each): $18239.52

**Comment by dlouise64** [comment]
![Screen Shot 2018-05-22 at 2.41.33 pm.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5d4e54c8f9d70012f9078a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f16b7191a37af1162a4f5c5c5eec1c4a4356bcbbd671f3e57862804e0ebcd86a5b71c23b44f9b9814db601ba21d94b8de2b48318d2f42f67b6d5db1063474f4dcbed5727a19e41c95df44de84853ad113067e07e2431.png)

Like this?

**Comment by dlouise64** [comment]
closes #262

**Comment by dlouise64** [comment]
@ssibbehh @Br3nda what should the partners total be, if partners NZ Superannuation is checked? Currently its $0
