### ISSUE TITLE
PDF Artefacts of the completed forms

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/pancake-frontend#431]
As a Tauranga CC staff member, i need to download the completed forms  as zip folder of PDFs) so i can send them to DIA

**Comment by Br3nda** [comment]
I've moved this to the Alpha milestone.

**Comment by Br3nda** [comment]
![image](https://user-images.githubusercontent.com/12266/43055578-6b7a3522-8e8b-11e8-93d8-e21a6d4f7ced.png)

**Comment by Br3nda** [comment]
https://app.atomic.io/d/aLcfshm97GUt

**Comment by Br3nda** [comment]
Just needs the images (DIA logo and the signatures) then i think i'm done.
