### ISSUE TITLE
Retrieve year from server and update on the front end

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/pancake-frontend#432]
Server says what year we are in.
Front-end asks and uses in the help text, application and openFisca

## Acceptance Criteria
- [ ] Backend works out which year we are running in, exposes on an API
- [ ] Front end reads and uses everywhere
- [ ] Uses year in calls to Open Fisca
- [ ] in pdfs
- [ ] Pick the correct year when displaying rates in #show

needs #430

**Comment by Br3nda** [comment]
Not necesary
