### ISSUE TITLE
DIA Admin rights

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/pancake-frontend#434]
As a DIA admin, I can CRUD (create, read, update, delete) users

**Comment by Br3nda** [comment]
I've started on this -- Is it three roles @ssibbehh  ?

Are these names good?

* DIA
* Council Rates staff
* Council frontline staff

Which types of user can do this:
* Deactivate another user
* Invite a new user
* View the list of users.

**Comment by ssibbehh** [comment]
@Br3nda 
Name are good
I think:

**Council rates staff:**
Deactivate another user
Invite a new user
View the list of users.

**Council frontline staff:**
Invite a new user

Do you agree?

**Comment by Br3nda** [comment]
@ssibbehh how about Council Rates Staff can only create or see users at their own council

**Comment by ssibbehh** [comment]
@Br3nda yep - ah yes! very important point

**Comment by ssibbehh** [comment]
https://app.atomic.io/d/5u7f7ZQRiX96 admin wireframes
