### ISSUE TITLE
404 error @ serviceinnovationlab.github.io/pancake-frontend

### ISSUE THREAD

**Issue by PicoCreator** [ServiceInnovationLab/pancake-frontend#485]
![pancake-frontend-down](https://user-images.githubusercontent.com/17175484/43378582-6c29c356-93fa-11e8-952c-691cecfb24cc.gif)

I suspect the current build of gh-pages is broken

**Comment by Br3nda** [comment]
We turned off github pages. Is there a link somewhere to it?

**Comment by Br3nda** [comment]
Hi @PicoCreator We haven't been deploying to github pages for a while. I'll get that link removed from the readme
