### ISSUE TITLE
Rebate claimed showing at $620 not $630

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-frontend#494]

**Comment by ssibbehh** [comment]
![Screen Shot 2018-07-30 at 9.01.01 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa9a70d5cd4950011788690/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246457f36b7191a371f1122a4f5f5e5ecc3c4a4356bcbbd671f3e57862804e0ebcd86a5b71c23b44f9b9814db601ba21d94b8de2b48318d2f42f67b6d5db1063474f4dcbed5727a19e41c95df549e84954a7113764e6712431.png)

**Comment by dlouise64** [comment]
@ssibbehh @Br3nda  can confirm this has been fixed
<img width="920" alt="screen shot 2018-07-31 at 1 05 38 pm" src="https://user-images.githubusercontent.com/4723307/43431558-773531a4-94c2-11e8-8aee-581d3c66735b.png">
