### ISSUE TITLE
Comma functionality with income $$

### ISSUE THREAD

**Issue by gthurstonnz** [ServiceInnovationLab/pancake-frontend#502]
System – OS X 10.8.5
Processor 2.66 GHz Intel Core 2 Duo
Memory – 8GB 1067 MHz DDR3
Browser: Chrome Version 49.0.2623.112 (64-bit)

Went to add income and used a comma to do this.  Income calculation for salary and wages not included in total (no comma’s allowed):
![image](https://user-images.githubusercontent.com/41927851/43424499-cc190f16-94a3-11e8-968a-dbd4a556d4d8.png)

Was able to apply and exit. Got email.

**Comment by dlouise64** [comment]
@Br3nda ready to be tested again.
