### ISSUE TITLE
Error on Microsoft Edge

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-frontend#506]

**Comment by ssibbehh** [comment]
![IE.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa9a70d5cd4950011788690/125516c66e82c728ace21e0d46c1b1d86fc093bb80e3ba40b01faad67c477e247d51f77d7580b27bbd1b2b515e0d4aa415505610eee59b69f7e8682fd70541b8937f5566c7341badbd811db608bb24894d80b5bb9801.PNG)

**Comment by ssibbehh** [comment]
How I got there
![001.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa9a70d5cd4950011788690/125516c66e82c728ace21e0d46b8c4cb61cec1b99de6b546a749b2ce6b13262a7e50f67f2680e679ec4022515f5e1ca8490c574da8eb9539e4e76224d50152a7842f4d7ed43c18a6b9871cbd08b3218e4b81bfbd8c5e8d.PNG)
![002.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa9a70d5cd4950011788690/125516c66e82c728ace21e0d46b8c4c861cec1b99de6b546a749b2ce6b13262a7e50f67f2680e679ec4022515f5e1ca8490c574da8eb9539e4e76224d50152a7842f4d7ed43c16a6b9871cbd08b3218e4b82b0bd8e5e8d.PNG)
![003.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa9a70d5cd4950011788690/125516c66e82c728ace21e0d46b8c4c961cec1b99de6b546a749b2ce6b13262a7e50f67f2680e679ec4022515f5e1ca8490c574da8eb9539e4e76224d50152a7842f4d7ed43c16a6b9871cbd08b3218e4a84b2be8f5e8d.PNG)
![004.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa9a70d5cd4950011788690/125516c66e82c728ace21e0d46b8c4ce61cec1b99de6b546a749b2ce6b13262a7e50f67f2680e679ec4022515f5e1ca8490c574da8eb9539e4e76224d50152a7842f4d7ed43c16a6b9871cbd08b3218e4a81b4bc885e8d.PNG)

**Comment by ssibbehh** [comment]
Application did not come through to back end

**Comment by Br3nda** [comment]
Test again once https://github.com/ServiceInnovationLab/pancake-backend/pull/161 is merged


needs https://github.com/ServiceInnovationLab/pancake-backend/pull/161
