### ISSUE TITLE
Batch PDF issue 2018

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/pancake-frontend#550]
As a DIA admin, I need to have information to know if someone is eligible for a rebate so that i can pay the council the right amount. 

# Acceptance criteria
- [x] 1.	The batch header sheet says there are 96 applications, I assume this was meant to be 62?
- [x] 2.	There is no rates information entered for any application, although there is a field for 2019 rates ??

- [x] 4.	The ‘Did you live with a partner or a joint homeowner on 1 July?’ question never has a yes or no answer.
- [x] 5.	The PDF filenames do not reference the application in any way so they cannot easily be matched with their corresponding apps on eRMS. i.e we need the applicant name or TA Reference to be in the filename.

https://app.atomic.io/prototype/10bb2je-rebates-form/edit?page=b949e1bc-8085-4b2c-9735-a49bab7f177f

**Comment by dlouise64** [comment]
@ssibbehh Can you please log into production, and check no. 1 has been fixed? I believe it has.
3. 
I can name the individual pdf downloads but what should we name the batch file?

**Comment by Br3nda** [comment]
Will the council computers cope with that? People's names aren't all that safe. My name could be "../../..//etc/apt.d/source.list" .

**Comment by dlouise64** [comment]
Changing filename to "[council name]-[valuation id]-[rebate form id]" @Br3nda @ssibbehh

**Comment by Br3nda** [comment]
valuation IDs look like this: `06601*013*00*B`
How do different browsers and filesystems handle that asterisk? It might do really weird things
