### ISSUE TITLE
Mark in Database all properties that have received rebates throughout the year

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/pancake-frontend#79]
Sibby to get list of properties that have already received rates rebates

**Comment by Br3nda** [comment]
@ssibbehh do you want to do something different if the user has already received a rebate?
The user hasn't authenticated, so we can't give out the info on who has a rebate.

**Comment by ssibbehh** [comment]
I would like an error message: "Error - Please contact the council on XX-XXX-XXX"
Will chase up data of previous applicants now

**Comment by Br3nda** [comment]
As discussed at sprint planning - Closing this for now
