### ISSUE TITLE
Add spouse income to openfisca input form on the app.

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/pancake-frontend#84]

**Comment by MattiSG** [comment]
According to https://github.com/ServiceInnovationLab/openfisca-aotearoa/blob/6d623445b98d746adb14aa79a0b1795776d881c1/openfisca_aotearoa/variables/ratesrebates.py#L47, all the income of “members” of a property are taken into account. These members are defined in the Propertee entity as `owner` or `tenant`: https://github.com/ServiceInnovationLab/openfisca-aotearoa/blob/6d623445b98d746adb14aa79a0b1795776d881c1/openfisca_aotearoa/entities.py#L27-L39

That means OpenFisca currently has no knowledge of a “spouse” role. This should be added as it models law. A workaround that could be used in production today would be to define spouses as `tenant` (or `owner`, but there can be at most 2 owners according to the current Propertee definition) in the API call.

**Comment by dlouise64** [comment]
Combine applicant and spouse income

**Comment by Br3nda** [comment]
Let's close this, we don't need it
